[project]
name = 'Decentralized-Freelance-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escrow-service]
path = 'contracts/escrow-service.clar'
clarity_version = 2
epoch = 2.5

[contracts.job-posting]
path = 'contracts/job-posting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
